apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-gcp-secret
  title: Create/Update Secrets in GCP
  description: Crie ou atualize múltiplos secrets no GCP Secret Manager.
  tags:
    - gcp
    - secret-manager
spec:
  owner: guest
  type: service
  parameters:
    - title: Configuração do Projeto
      required: [project_id]
      properties:
        project_id:
          title: Projeto GCP
          type: string
          enum:
            - devops-labs-397603
            # - jeitto-pre-prod
            # - jeitto-prod
            
    - title: Adicionar Secrets
      required: [secrets_list]
      properties:
        secrets_list:
          title: Lista de Secrets
          description: Clique em "+" para adicionar mais secrets
          type: array
          minItems: 1
          items:
            type: object
            required:[name, value]
            properties:
              name:
                title: Secret ID
                type: string
                description: "Ex: MINHA_VARIAVEL_GKE_<ENV>"
                pattern: '^[A-Z0-9_]+$'
              value:
                title: Secret Value
                type: string
                ui:widget: password # Esconde o valor na tela igual senha
                ui:backstage:
                  review:
                    mask: true # Esconde no resumo final (Review) da tela

  steps:
    - id: upsert-gcp-secrets
      name: Criando e Atualizando Secrets no GCP
      action: gcp:secrets-manager:upsert
      input:
        project: ${{ parameters.project_id }}
        secrets: ${{ parameters.secrets_list }}

  output:
    links:
      - title: Acessar Secret Manager no GCP
        url: https://console.cloud.google.com/security/secret-manager?project=${{ parameters.project_id }}
