apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-gcp-secret
  title: Create or Update Secrets in GCP
  description: Template para criar ou atualizar múltiplos secrets no GCP Secret Manager
  tags:
    - gcp
    - secret-manager
spec:
  owner: guest
  type: service
  
  parameters:
    - title: Tipo de Operação
      required:
        - operation_type
      properties:
        operation_type:
          title: O que você deseja fazer?
          type: string
          enum:
            - create
            - update
          enumNames:
            - 'Criar novo(s) Secret(s)'
            - 'Atualizar Secret(s) Existente(s)'
          default: create
          ui:widget: radio

    - title: Projeto e Configurações
      required: 
        - project_id
        - secrets
      properties:
        project_id:
          title: Projeto GCP
          type: string
          enum:
            - devops-labs-397603
        
        secrets:
          title: Lista de Secrets
          description: Clique no botão de "+" ou "Add Item" para incluir vários secrets de uma vez.
          type: array
          minItems: 1
          items:
            type: object
            required: 
              - name
              - value
            properties:
              name:
                title: Secret ID (Chave)
                description: "Ex: GKE_INTEGRATION_MINHA_VARIAVEL"
                type: string
                pattern: '^[A-Z0-9_]+$'
              value:
                title: Secret Value (Valor)
                type: string
                ui:backstage:
                  review:
                    mask: true 
  steps:
    - id: upsert-secrets-action
      name: Executando Operação no GCP
      action: gcp:secrets-manager:upsert
      input:
        project: ${{ parameters.project_id }}
        operation: ${{ parameters.operation_type }}
        secrets: ${{ parameters.secrets }}

  output:
    links:
      - title: Visualizar Secrets no Console do GCP
        url: https://console.cloud.google.com/security/secret-manager?project=${{ parameters.project_id }}
